name: Deploy to Koyeb

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Koyeb
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{}' https://api.koyeb.com/functions/your-function-endpoint # Replace 'your-function-endpoint' with the actual HTTP endpoint
        env:
          KOYEB_API_KEY: ${{ secrets.ny5lg85nnqz9wihnvsvt9pbbfovjenr9bstb4qqwsv41q1yjk95938xihj55zyaj }}


